name: CINC SA de CV
favicon: null
layout_spectrum: 0.35309
typography_spectrum: 0.92547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ed4630'
    - '#020202'
    - '#f8cbc9'
    - '#626262'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
